version: "3.8"

services:
  weather-api:
    image: flask-clima:latest
    build: .
    container_name: flask-clima
    ports:
      - "5000:5000"
    environment:
      - API_KEY=${API_KEY}
    restart: unless-stopped
